# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rails', '~> 5.0'
gem 'rubocop', '~> 0.80.0'
gem 'ruby-lsp', '~> 0.0.1'
gem 'sqlite3', '~> 1.4', '>= 1.4.4'
gem 'spring', '~> 2.0', '>= 2.0.2'
gem 'minitest', '~> 5.15'
gem 'puma', '~> 5.6', '>= 5.6.8'
