# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rails', '~> 5.0'
gem 'rubocop', '~> 0.80.0'
gem 'ruby-lsp', '~> 0.0.1'
gem 'sqlite3', '~> 1.4', '>= 1.4.4'
