# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rails', '~> 4.0', '>= 4.0.13'
gem 'rubocop', '~> 0.34.0'
gem 'json', '~> 2.3'
